"""Phase 13 — Report and Cost/Resource Generator.

Two public classes
------------------
CostReportGenerator
    Accepts the stored experiment dict (from ExperimentManager.get_experiment())
    and produces a cost_report dict whose shape matches contracts/cost_report.json.

ReportGenerator
    Accepts the same experiment dict (plus an optional cost report and optional
    explanation dicts) and produces a full 16-section HTML experiment report.
    Also persists the report to artifacts/reports/{experiment_id}_report.html.

Design rules
------------
- Never retrain or call model.fit().
- Never claim medical causality or diagnoses.
- Never interpret an uncalibrated score as a clinical probability.
- Never claim quantum advantage is proven — only "observed on this dataset".
- financial_cost_local.estimate is ALWAYS 0 for local runs.
- The HTML report MUST contain the heading "RESEARCH / BENCHMARKING SYSTEM".

Compatibility
-------------
Works from the serialised experiment dict stored by ExperimentManager.  The
generator never imports live model objects; it only reads dicts. This means
it is safe to call from the FastAPI layer without PennyLane in scope.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from backend.core.logging import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REPORTS_DIR = Path("./artifacts/reports")

_RESEARCH_DISCLAIMER = (
    "RESEARCH / BENCHMARKING SYSTEM — outputs are for scientific investigation "
    "only. Predictions generated by this platform are NOT clinical diagnoses. "
    "Results must not be used for medical decisions. Model scores are "
    "uncalibrated and must not be interpreted as clinical probabilities. "
    "Explanations describe model behaviour, not medical causality."
)

_ALL_MODELS = ("logistic_regression", "svm", "random_forest", "vqc")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_float(v: Any, default: float = 0.0) -> float:
    try:
        return float(v) if v is not None else default
    except (TypeError, ValueError):
        return default


def _safe_int(v: Any, default: int = 0) -> int:
    try:
        return int(v) if v is not None else default
    except (TypeError, ValueError):
        return default


def _pct(value: float, total: float) -> float:
    return round(value / total * 100, 1) if total > 0 else 0.0


def _fmt_pct(v: Any) -> str:
    try:
        return f"{float(v):.1%}"
    except (TypeError, ValueError):
        return "N/A"


def _fmt_f(v: Any, decimals: int = 4) -> str:
    try:
        return f"{float(v):.{decimals}f}"
    except (TypeError, ValueError):
        return "N/A"


def _fmt_s(v: Any, decimals: int = 2) -> str:
    try:
        return f"{float(v):.{decimals}f}s"
    except (TypeError, ValueError):
        return "N/A"


def _scalability_verdict(n_qubits: int) -> dict:
    if n_qubits <= 8:
        status = "FEASIBLE"
        note = (
            f"{n_qubits} qubits: feasible on a standard laptop. "
            "Statevector simulation requires O(2^n) memory; 8 qubits ≈ 2KB state vector."
        )
    elif n_qubits <= 12:
        status = "FEASIBLE_HIGH_RESOURCE"
        note = (
            f"{n_qubits} qubits: feasible but requires elevated RAM (6–16 GB). "
            "Not recommended for standard laptops."
        )
    else:
        status = "NOT_RECOMMENDED_LOCAL"
        note = (
            f"{n_qubits} qubits: NOT recommended for local simulation. "
            "Memory requirements grow exponentially (2^n amplitudes)."
        )
    return {
        "current_environment":    "LOCAL_LAPTOP",
        "this_experiment_status": status,
        "recommended_max_qubits": 8,
        "note":                   note,
    }


def _deployment_verdict(n_qubits: int, quantum_worse: bool) -> dict:
    if quantum_worse:
        readiness = "NOT_RECOMMENDED_PRODUCTION"
        reasons = [
            "Classical baseline achieves comparable or higher performance.",
            "Quantum simulation adds significant compute cost.",
            f"{n_qubits}-qubit VQC suitable for research/validation — not production.",
        ]
        alternative = (
            "Deploy the best classical model for production. "
            "Use VQC results for continued research benchmarking."
        )
    else:
        readiness = "RESEARCH_ONLY"
        reasons = [
            "Quantum model shows promising results on this dataset.",
            "Results require validation on larger, independent datasets.",
            "Local simulator output — real quantum hardware evaluation needed.",
        ]
        alternative = (
            "Continue research evaluation before production deployment. "
            "Validate results on independent datasets."
        )
    return {
        "production_readiness": readiness,
        "reasons":              reasons,
        "alternative":          alternative,
    }


# ---------------------------------------------------------------------------
# CostReportGenerator
# ---------------------------------------------------------------------------

class CostReportGenerator:
    """Generates the cost_report dict matching contracts/cost_report.json.

    Accepts the experiment dict returned by ExperimentManager.get_experiment()
    — i.e., ``experiment["results"]`` already contains serialised model dicts.

    Usage
    -----
    generator = CostReportGenerator()
    cost_report = generator.generate(experiment)
    """

    def generate(self, experiment: dict) -> dict:
        """Build cost report from a stored experiment dict.

        Parameters
        ----------
        experiment : dict
            Full experiment dict as returned by
            ``ExperimentManager.get_experiment()``.

        Returns
        -------
        dict matching contracts/cost_report.json
        """
        experiment_id = experiment.get("id", "UNKNOWN")
        dataset_id    = experiment.get("dataset_id", "UNKNOWN")
        results       = experiment.get("results", {})
        models        = results.get("models", {})
        comparison    = results.get("comparison", {})
        resource_usage = results.get("resource_usage", {})
        preprocessing  = results.get("preprocessing", {})

        logger.info(f"CostReportGenerator: generating cost report for {experiment_id}")

        # ── Find best quantum model (by ROC-AUC) ─────────────────────────
        quantum_models = {
            k: v for k, v in models.items()
            if v.get("model_type") == "QUANTUM" or k.lower() in ("vqc", "quantumsvm")
        }
        best_q_name = "N/A"
        best_q_data = {}
        best_q_auc = -1.0
        for qname, qdata in quantum_models.items():
            qm = (qdata or {}).get("metrics", {})
            qauc = _safe_float(qm.get("roc_auc"))
            if qauc > best_q_auc:
                best_q_auc = qauc
                best_q_name = qname
                best_q_data = qdata

        best_q_metrics = best_q_data.get("metrics", {})
        q_res = best_q_data.get("quantum_metrics", best_q_metrics.get("quantum_resources", {}))

        n_qubits      = _safe_int(q_res.get("qubits", q_res.get("n_qubits")), 8)
        n_layers      = _safe_int(q_res.get("n_layers"), 2)
        n_params      = _safe_int(q_res.get("n_params"), 0)
        circuit_depth = _safe_int(q_res.get("circuit_depth"), 0)
        n_executions  = _safe_int(q_res.get("total_circuit_executions", q_res.get("n_circuit_executions")), 0)
        shots         = q_res.get("shots")           # may be None (exact simulation)
        q_train_t     = _safe_float(
            best_q_data.get("resource_usage", {}).get("training_time_seconds",
            best_q_data.get("training_time")), 0.0
        )
        q_infer_t     = _safe_float(
            best_q_data.get("resource_usage", {}).get("inference_time_seconds",
            best_q_data.get("inference_time")), 0.0
        )

        # Derived quantum metrics not stored directly
        cnot_per_layer = (n_qubits * (n_qubits - 1)) // 2
        gate_count_est = (
            n_qubits                             # encoding RY
            + n_layers * n_qubits * 2            # RY + RZ per layer
            + n_layers * cnot_per_layer          # CNOTs per layer
        )
        two_qubit_gates_est = n_layers * cnot_per_layer

        # Performance summary for best quantum
        q_perf = {
            "accuracy":    round(_safe_float(best_q_metrics.get("accuracy")), 4),
            "recall":      round(_safe_float(best_q_metrics.get("recall")), 4),
            "specificity": round(_safe_float(best_q_metrics.get("specificity")), 4),
            "roc_auc":     round(_safe_float(best_q_metrics.get("roc_auc")), 4),
        }

        # ── Classical best model ──────────────────────────────────────
        best_classical_name = comparison.get("best_classical") or "random_forest"
        best_cl_data   = models.get(best_classical_name, {})
        best_cl_train  = _safe_float(best_cl_data.get("training_time"), 0.001)
        best_cl_metrics = best_cl_data.get("metrics", {})
        best_cl_auc    = _safe_float(best_cl_metrics.get("roc_auc"))
        best_cl_recall = _safe_float(best_cl_metrics.get("recall"))

        # ── Pipeline timing breakdown ─────────────────────────────────
        total_pipeline = _safe_float(resource_usage.get("elapsed_time"), 0.0)
        # Fall back: sum of all model training times
        if total_pipeline < 1e-6:
            total_pipeline = sum(
                _safe_float(m.get("training_time")) + _safe_float(m.get("inference_time"))
                for m in models.values()
            )

        # Estimate preprocessing time: total minus all model times
        model_total = sum(
            _safe_float(m.get("training_time")) + _safe_float(m.get("inference_time"))
            for m in models.values()
        )
        preprocess_est = max(0.0, total_pipeline - model_total)

        quantum_pct = _pct(q_train_t + q_infer_t, total_pipeline)

        # ── RAM ───────────────────────────────────────────────────────
        peak_memory_mb = _safe_float(resource_usage.get("peak_memory_mb"))
        ram_peak_gb    = round(peak_memory_mb / 1024.0, 3)
        cpu_avg        = round(_safe_float(resource_usage.get("cpu_percent")), 1)

        # ── Classical comparison verdict ──────────────────────────────
        if best_cl_train > 1e-6:
            speedup = round(q_train_t / best_cl_train, 1)
        else:
            speedup = 0.0

        q_auc = q_perf["roc_auc"]
        auc_diff = round(q_auc - best_cl_auc, 4)
        quantum_worse = auc_diff < 0

        if quantum_worse:
            verdict = (
                f"Classical {best_classical_name} achieves {-auc_diff:.3f} higher ROC-AUC "
                f"and trains {speedup:.1f}x faster. "
                f"Classical model preferred for this dataset/configuration."
            )
        elif auc_diff > 0.02:
            verdict = (
                f"{best_q_name} achieves +{auc_diff:.3f} higher ROC-AUC than {best_classical_name}, "
                f"but trains {speedup:.1f}x slower. "
                f"Promising quantum result -- observed on this dataset only."
            )
        else:
            verdict = (
                f"{best_q_name} and {best_classical_name} show comparable ROC-AUC (delta={auc_diff:+.3f}). "
                f"{best_q_name} trains {speedup:.1f}x slower. "
                f"Performance parity -- classical preferred for efficiency."
            )

        # ── Scalability ───────────────────────────────────────────────
        scalability = _scalability_verdict(n_qubits)

        # ── Deployment recommendation ─────────────────────────────────
        deployment = _deployment_verdict(n_qubits, quantum_worse)

        # ── Original feature count ────────────────────────────────────
        original_features = _safe_int(preprocessing.get("original_features"), 0)
        reduced_features  = _safe_int(preprocessing.get("reduced_features"), n_qubits)

        cost_report = {
            "experiment_id":   experiment_id,
            "experiment_type": "QUANTUM_CLASSICAL_HYBRID",
            "model_type":      f"{best_q_name} + Classical Ensemble",
            "dataset_id":      dataset_id,
            "report_timestamp": datetime.now(timezone.utc).isoformat(),

            "performance_summary": q_perf,

            "computational_cost": {
                "training": {
                    "wall_clock_time_seconds":    round(q_train_t, 2),
                    "cpu_utilization_avg_percent": cpu_avg,
                    "ram_peak_gb":                ram_peak_gb,
                    "ram_peak_mb":                round(peak_memory_mb, 1),
                },
                "inference": {
                    "avg_time_ms": round(q_infer_t * 1000, 1),
                },
            },

            "quantum_cost": {
                "qubits":                   n_qubits,
                "n_layers":                 n_layers,
                "n_params":                 n_params,
                "circuit_depth":            circuit_depth,
                "gate_count":               gate_count_est,
                "two_qubit_gates":          two_qubit_gates_est,
                "shots_per_execution":      shots,
                "total_circuit_executions": n_executions,
                "total_shots": (
                    n_executions * shots if shots and n_executions else None
                ),
            },

            "pipeline_cost_breakdown": {
                "preprocessing_seconds":    round(preprocess_est, 2),
                "quantum_training_seconds": round(q_train_t, 2),
                "total_pipeline_seconds":   round(total_pipeline, 2),
                "quantum_percentage":       quantum_pct,
            },

            "comparison_classical_baseline": {
                "classical_model":         best_classical_name,
                "classical_training_secs": round(best_cl_train, 4),
                "quantum_training_secs":   round(q_train_t, 2),
                "speedup_classical":       speedup,
                "classical_roc_auc":       round(best_cl_auc, 4),
                "quantum_roc_auc":         q_auc,
                "verdict":                 verdict,
            },

            "scalability_assessment": scalability,

            "financial_cost_local": {
                "infrastructure":          "LOCAL_LAPTOP",
                "financial_cost_estimate": 0,
                "cost_units": {
                    "cpu_core_hours": round(q_train_t / 3600, 4),
                    "ram_gb_hours":   round(ram_peak_gb * q_train_t / 3600, 4),
                },
                "note": "Local execution — no cloud quantum cost. "
                        "Financial estimate = 0.",
            },

            "resource_feasibility": {
                "current_environment":     "LOCAL_LAPTOP",
                "this_experiment_status":  scalability["this_experiment_status"],
                "bottleneck": (
                    f"Quantum training time ({round(q_train_t, 1)}s) "
                    f"dominated pipeline ({quantum_pct}%)."
                    if quantum_pct > 50 else
                    f"RAM usage peaked at {round(peak_memory_mb, 0):.0f} MB."
                ),
            },

            "deployment_recommendation": deployment,

            "feature_reduction_info": {
                "original_features":  original_features,
                "reduced_features":   reduced_features,
                "method":             "PCA",
                "note": (
                    "Feature reduction is not optional — it makes the quantum "
                    "branch computationally feasible by mapping high-dimensional "
                    "data to the qubit count."
                ),
            },

            "warnings": [
                "These results are specific to the evaluated dataset and "
                "experimental configuration.",
                "Local simulator results may differ from real quantum hardware.",
                "Model scores are uncalibrated and must not be interpreted as "
                "clinical probabilities.",
                "RESEARCH / BENCHMARKING SYSTEM — not a clinical diagnosis.",
            ],
        }

        logger.info(
            f"CostReportGenerator: done. "
            f"quantum_pct={quantum_pct}%, "
            f"financial_cost=0"
        )
        return cost_report

    def save(self, cost_report: dict, experiment_id: str) -> str:
        """Persist cost report as JSON.

        Saves to ``artifacts/reports/{experiment_id}_cost_report.json``.

        Returns
        -------
        str — absolute path to the written file.
        """
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        path = REPORTS_DIR / f"{experiment_id}_cost_report.json"
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(cost_report, fh, indent=2, default=str)
        logger.info(f"Cost report saved: {path}")
        return str(path)


# ---------------------------------------------------------------------------
# ReportGenerator
# ---------------------------------------------------------------------------

class ReportGenerator:
    """Generates the full 16-section HTML experiment report.

    Usage
    -----
    generator = ReportGenerator()
    html = generator.generate(experiment, cost_report, explanations)
    path = generator.save(html, experiment_id)
    """

    # ── HTML shell ─────────────────────────────────────────────────────────

    _CSS = """
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                     'Helvetica Neue', Arial, sans-serif;
        line-height: 1.65; color: #1a1a2e; background: #f0f2f5;
    }
    .page { max-width: 1100px; margin: 30px auto; background: #fff;
            border-radius: 10px; box-shadow: 0 4px 24px rgba(0,0,0,.12);
            overflow: hidden; }
    /* Header */
    .hdr { background: linear-gradient(135deg,#0f3460 0%,#533483 100%);
           color: #fff; padding: 40px 48px; }
    .hdr h1 { font-size: 2em; letter-spacing: -.5px; margin-bottom: 6px; }
    .hdr .sub { font-size: 1.1em; opacity: .85; margin-bottom: 18px; }
    .hdr .meta { font-size: .88em; opacity: .75; }
    /* Disclaimer banner */
    .banner { background: #fff3e0; border-left: 6px solid #f57c00;
              padding: 16px 24px; margin: 0; font-size: .95em; }
    .banner strong { color: #e65100; }
    /* Content */
    .content { padding: 36px 48px; }
    h2 { font-size: 1.35em; color: #0f3460; margin: 36px 0 14px;
         padding-bottom: 6px; border-bottom: 2px solid #0f3460; }
    h3 { font-size: 1.05em; color: #533483; margin: 20px 0 10px; }
    p  { margin-bottom: 10px; }
    ul { margin: 8px 0 12px 22px; }
    li { margin-bottom: 4px; }
    /* KPI cards */
    .cards { display: flex; flex-wrap: wrap; gap: 14px; margin: 14px 0 20px; }
    .card { flex: 1 1 160px; background: linear-gradient(135deg,#f5f7fa,#c3cfe2);
            border-left: 4px solid #0f3460; border-radius: 8px; padding: 16px 18px; }
    .card .lbl { font-size: .78em; color: #555; text-transform: uppercase;
                 letter-spacing: .5px; font-weight: 600; }
    .card .val { font-size: 1.7em; font-weight: 700; color: #1a1a2e; margin-top: 4px; }
    /* Tables */
    table { width: 100%; border-collapse: collapse; margin: 14px 0 20px;
            font-size: .93em; border-radius: 6px; overflow: hidden;
            box-shadow: 0 1px 6px rgba(0,0,0,.07); }
    th { background: #0f3460; color: #fff; padding: 12px 14px;
         text-align: left; font-weight: 600; }
    td { padding: 11px 14px; border-bottom: 1px solid #e8e8e8; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f7f8ff; }
    .hl td { background: #e8f5e9 !important; font-weight: 600; }
    .q-row td:first-child { color: #533483; font-weight: 600; }
    /* Badges */
    .badge { display: inline-block; padding: 2px 9px; border-radius: 12px;
             font-size: .8em; font-weight: 600; }
    .b-cl { background: #e3f2fd; color: #1565c0; }
    .b-q  { background: #f3e5f5; color: #6a1b9a; }
    /* Recommendation box */
    .rec { background: #f3e5f5; border-left: 5px solid #6a1b9a;
           border-radius: 6px; padding: 18px 22px; margin: 14px 0; }
    .rec .title { font-weight: 700; color: #4a148c; margin-bottom: 6px; }
    /* Warning / disclaimer blocks */
    .warn { background: #fff8e1; border-left: 4px solid #ffa000;
            padding: 14px 18px; border-radius: 4px; margin: 12px 0;
            font-size: .92em; color: #5d4037; }
    .footer { background: #f5f5f5; padding: 18px 48px; text-align: center;
              color: #888; font-size: .85em; border-top: 1px solid #e0e0e0; }
    code { background: #f0f4f8; padding: 1px 5px; border-radius: 3px;
           font-size: .9em; }
    """

    def generate(
        self,
        experiment: dict,
        cost_report: Optional[dict] = None,
        explanations: Optional[dict] = None,
    ) -> str:
        """Build the full 16-section HTML report string.

        Parameters
        ----------
        experiment : dict
            Full experiment dict from ExperimentManager.get_experiment().
        cost_report : dict, optional
            Output of CostReportGenerator.generate(). Generated on the fly
            if not supplied.
        explanations : dict, optional
            Dict keyed by model name with explanation data
            (matches contracts/explanation.json shape).

        Returns
        -------
        str — complete HTML document.
        """
        if cost_report is None:
            cost_report = CostReportGenerator().generate(experiment)

        experiment_id = experiment.get("experiment_id") or experiment.get("id") or "UNKNOWN"
        results       = experiment.get("results", {})
        models        = results.get("models", {})
        comparison    = results.get("comparison", {})
        pipeline_info = results.get("pipeline_info", {})
        dataset_profile = results.get("dataset_profile") or pipeline_info
        preprocessing   = results.get("preprocessing") or pipeline_info
        resource_usage  = results.get("resource_usage") or pipeline_info
        configuration   = experiment.get("configuration") or {}
        explanations    = explanations or {}

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        sections: List[str] = [
            self._s1_executive_summary(experiment_id, models, comparison),
            self._s2_dataset_profile(dataset_profile, preprocessing),
            self._s3_experiment_plan(configuration, preprocessing),
            self._s4_classical_results(models),
            self._s5_quantum_results(models),
            self._s6_model_comparison(models),
            self._s7_qvc_assessment(comparison, cost_report),
            self._s8_classical_importance(models, explanations),
            self._s9_quantum_importance(explanations),
            self._s10_circuit_info(models, explanations),
            self._s11_resource_usage(models, resource_usage),
            self._s12_cost_analysis(cost_report),
            self._s13_pipeline_trace(explanations, configuration),
            self._s14_limitations(),
            self._s15_conclusion(comparison),
            self._s16_reproduction(experiment_id, configuration),
        ]

        section_html = "\n".join(sections)

        dataset_name = dataset_profile.get("name", "Unknown dataset")
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Q-Diagnose Experiment Report — {experiment_id}</title>
  <style>{self._CSS}</style>
</head>
<body>
<div class="page">

  <div class="hdr">
    <h1>&#128300; Q-Diagnose — Hybrid QML Experiment Report</h1>
    <div class="sub">
      QUANT WARRIORS &nbsp;|&nbsp; Hybrid Quantum-Classical Disease Detection Platform
    </div>
    <div class="meta">
      Generated: {timestamp} &nbsp;|&nbsp;
      Experiment: <strong>{experiment_id}</strong> &nbsp;|&nbsp;
      Dataset: {dataset_name}
    </div>
  </div>

  <div class="banner">
    <strong>&#9888;&#65039; RESEARCH / BENCHMARKING SYSTEM</strong> &mdash;
    {_RESEARCH_DISCLAIMER}
  </div>

  <div class="content">
    {section_html}
  </div>

  <div class="footer">
    Q-Diagnose MVP &nbsp;|&nbsp; Quant Warriors SIH 2026 &nbsp;|&nbsp;
    Report generated {timestamp} &nbsp;|&nbsp;
    Experiment {experiment_id}<br>
    <em>Not a clinical tool. For research and benchmarking purposes only.</em>
  </div>

</div>
</body>
</html>"""

        logger.info(f"ReportGenerator: HTML report built for {experiment_id}")
        return html

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _s1_executive_summary(
        self, experiment_id: str, models: dict, comparison: dict
    ) -> str:
        best_cl_info = comparison.get("best_classical") or comparison.get("classical_best") or "N/A"
        best_cl_name = best_cl_info.get("model_name", "N/A") if isinstance(best_cl_info, dict) else str(best_cl_info)

        best_q_info = comparison.get("best_quantum") or comparison.get("quantum_best") or "N/A"
        best_q_name = best_q_info.get("model_name", "N/A") if isinstance(best_q_info, dict) else str(best_q_info)

        best_info = comparison.get("best_overall") or comparison.get("best_model") or best_cl_name
        best_name = best_info.get("model_name", "N/A") if isinstance(best_info, dict) else str(best_info)

        rec = comparison.get("recommendation_text") or comparison.get("recommendation") or "See model comparison section."

        # KPI cards — dynamic
        best_cl_data = models.get(best_cl_name) or (best_cl_info if isinstance(best_cl_info, dict) else {})
        best_cl_metrics = (best_cl_data.get("metrics") if isinstance(best_cl_data, dict) else {}) or {}
        quantum_models = {k: v for k, v in models.items() if str(v.get("model_type", "")).upper() == "QUANTUM"}
        classical_models = {k: v for k, v in models.items() if str(v.get("model_type", "")).upper() != "QUANTUM"}

        card_items = [
            ("Best Classical", best_cl_name.replace("_", " ").title()),
            ("Best Overall",   best_name.replace("_", " ").title()),
            ("Classical AUC",  _fmt_f(best_cl_metrics.get("roc_auc"), 3)),
        ]
        for qname, qdata in quantum_models.items():
            qm = (qdata or {}).get("metrics", {})
            card_items.append((f"{qname} AUC", _fmt_f(qm.get("roc_auc"), 3)))

        cards = self._cards(card_items)

        # Build dynamic model list text
        cl_names = ", ".join(
            f"<strong>{n.replace('_', ' ').title()}</strong>"
            for n in classical_models
        )
        q_names = ", ".join(
            f"<strong>{n}</strong>"
            for n in quantum_models
        )
        n_models = len(models)

        return f"""
<h2>1. Executive Summary</h2>
{cards}
<p>
  This experiment evaluated {n_models} models on a biomedical binary classification task:
  {cl_names} (classical), and
  {q_names} (quantum).
</p>
<div class="rec">
  <div class="title">System Assessment</div>
  <p>{rec}</p>
</div>
<p class="warn">
  <strong>Research note:</strong> All conclusions are observed on the evaluated
  dataset and configuration only. They do not constitute proof of general quantum
  advantage or clinical efficacy.
</p>"""

    def _s2_dataset_profile(self, profile: dict, preprocessing: dict) -> str:
        name       = profile.get("name") or profile.get("dataset_name", "Biomedical Dataset")
        n_tr       = profile.get("n_train", 0)
        n_te       = profile.get("n_test", 0)
        rows       = profile.get("rows") or profile.get("n_samples") or (n_tr + n_te if n_tr or n_te else "?")
        col_data   = profile.get("columns", [])
        n_cols     = len(col_data) if isinstance(col_data, list) and col_data else profile.get("n_columns") or profile.get("n_features", "?")
        target     = profile.get("recommended_target") or profile.get("target", "Target")
        missing    = profile.get("missing_values_total", 0)
        is_binary  = profile.get("is_binary_classification", True)
        orig_feats = preprocessing.get("original_features") or preprocessing.get("n_features", "?")
        red_feats  = preprocessing.get("reduced_features") or preprocessing.get("n_components", "?")

        cards = self._cards([
            ("Dataset",    name),
            ("Rows",       str(rows)),
            ("Columns",    str(n_cols)),
            ("Target",     str(target)),
            ("Missing",    str(missing)),
            ("Task",       "Binary Classification" if is_binary else "Classification"),
        ])

        red_info = preprocessing.get("reduction", {})
        variance = red_info.get("cumulative_variance") or preprocessing.get("variance_retained")
        var_str  = f"{float(variance):.1%}" if variance is not None else "N/A"

        return f"""
<h2>2. Dataset Profile</h2>
{cards}
<h3>Feature Reduction</h3>
<table>
  <tr><th>Step</th><th>Detail</th></tr>
  <tr><td>Original features</td><td>{orig_feats}</td></tr>
  <tr><td>After PCA</td><td>{red_feats} components</td></tr>
  <tr><td>Variance retained</td><td>{var_str}</td></tr>
  <tr><td>Quantum input</td><td>{red_feats} features → {red_feats} qubits</td></tr>
</table>
<p class="warn">
  Feature reduction is not optional — it makes the quantum branch computationally
  feasible by mapping high-dimensional inputs to the qubit count.
</p>"""

    def _s3_experiment_plan(self, configuration: dict, preprocessing: dict) -> str:
        n_comp   = configuration.get("n_components") or preprocessing.get("n_components") or preprocessing.get("reduced_features", "?")
        q_cfg    = configuration.get("quantum_config", {})
        n_layers = q_cfg.get("layers", 2)
        shots    = q_cfg.get("shots", "N/A")
        rng      = configuration.get("random_state", 42)
        adapter  = configuration.get("adapter", "auto")
        split_strat = preprocessing.get("split_strategy", "80/20 stratified")

        return f"""
<h2>3. Experiment Plan</h2>
<table>
  <tr><th>Setting</th><th>Value</th></tr>
  <tr><td>Classical models</td><td>Logistic Regression, SVM, Random Forest</td></tr>
  <tr><td>Quantum model</td><td>VQC, QuantumSVM</td></tr>
  <tr><td>Feature reduction</td><td>PCA → {n_comp} components</td></tr>
  <tr><td>VQC layers</td><td>{n_layers}</td></tr>
  <tr><td>Shots (resource record)</td><td>{shots}</td></tr>
  <tr><td>Train/test split</td><td>{split_strat}</td></tr>
  <tr><td>Random state</td><td>{rng}</td></tr>
  <tr><td>Dataset adapter</td><td>{adapter or "auto"}</td></tr>
  <tr><td>Quantum backend</td><td>PennyLane local simulator (default.qubit)</td></tr>
</table>"""

    def _s4_classical_results(self, models: dict) -> str:
        classical = {k: v for k, v in models.items() if str(v.get("model_type", "")).upper() == "CLASSICAL"}
        if not classical:
            return "<h2>4. Classical Models — Results</h2><p>No classical results available.</p>"

        rows = ""
        for name, data in classical.items():
            m = data.get("metrics", {})
            t_train = data.get("resource_usage", {}).get("training_time_seconds") if isinstance(data.get("resource_usage"), dict) else data.get("training_time")
            f1_val = m.get("f1_score", m.get("f1"))
            rows += (
                f"<tr>"
                f"<td>{name.replace('_', ' ').title()}</td>"
                f"<td>{_fmt_pct(m.get('accuracy'))}</td>"
                f"<td>{_fmt_pct(m.get('recall'))}</td>"
                f"<td>{_fmt_pct(m.get('specificity'))}</td>"
                f"<td>{_fmt_pct(f1_val)}</td>"
                f"<td>{_fmt_f(m.get('roc_auc'), 4)}</td>"
                f"<td>{_fmt_s(t_train)}</td>"
                f"</tr>\n"
            )

        return f"""
<h2>4. Classical Models — Results</h2>
<table>
  <tr>
    <th>Model</th><th>Accuracy</th><th>Recall</th>
    <th>Specificity</th><th>F1</th><th>ROC-AUC</th><th>Train Time</th>
  </tr>
  {rows}
</table>
<p class="warn">
  Recall / sensitivity is highlighted because missing a positive case (false
  negative) carries higher clinical risk in disease screening applications.
  Higher recall reduces false negatives at the potential cost of false positives.
</p>"""

    def _s5_quantum_results(self, models: dict) -> str:
        quantum = {k: v for k, v in models.items() if v.get("model_type") == "QUANTUM"}
        if not quantum:
            return "<h2>5. Quantum Models -- Results</h2><p>No quantum model results available.</p>"

        subsections = ""
        for idx, (name, data) in enumerate(quantum.items()):
            m = data.get("metrics", {})
            qm = data.get("quantum_metrics", {})
            display = name.replace("_", " ").title()
            subsections += f"""
<h3>5.{idx + 1} {display} <span class="badge b-q">Quantum</span></h3>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Accuracy</td>    <td>{_fmt_pct(m.get('accuracy'))}</td></tr>
  <tr><td>Recall</td>      <td>{_fmt_pct(m.get('recall'))}</td></tr>
  <tr><td>Specificity</td> <td>{_fmt_pct(m.get('specificity'))}</td></tr>
  <tr><td>F1</td>          <td>{_fmt_pct(m.get('f1_score', m.get('f1')))}</td></tr>
  <tr><td>ROC-AUC</td>     <td>{_fmt_f(m.get('roc_auc'), 4)}</td></tr>
  <tr><td>Train time</td>  <td>{_fmt_s(data.get('resource_usage', {}).get('training_time_seconds', data.get('training_time')))}</td></tr>
  <tr><td>Qubits</td>      <td>{qm.get('qubits', 'N/A')}</td></tr>
  <tr><td>Circuit depth</td><td>{qm.get('circuit_depth', 'N/A')}</td></tr>
  <tr><td>Gate count</td>   <td>{qm.get('gate_count', 'N/A')}</td></tr>
  <tr><td>Circuit executions</td><td>{qm.get('total_circuit_executions', 'N/A')}</td></tr>
  <tr><td>Encoding</td>    <td>{qm.get('encoding_method', 'N/A')}</td></tr>
  <tr><td>Backend</td>     <td>{qm.get('backend_type', 'LOCAL_SIMULATOR')}</td></tr>
</table>
"""
        return f"""
<h2>5. Quantum Models -- Results</h2>
{subsections}
<p class="warn">
  Quantum scores are produced by a local quantum <em>simulator</em>, not real quantum
  hardware. Results may differ on actual quantum devices due to noise and
  decoherence.
</p>"""

    def _s6_model_comparison(self, models: dict) -> str:
        rows = ""
        # Enforce consistent order: LR, SVM, RF, VQC
        ordered = [(n, models[n]) for n in _ALL_MODELS if n in models]
        # Append any extra models not in the canonical list
        ordered += [(n, v) for n, v in models.items() if n not in _ALL_MODELS]

        for name, data in ordered:
            m     = data.get("metrics", {})
            mtype = str(data.get("model_type", "")).upper()
            is_q  = (mtype == "QUANTUM")
            badge = '<span class="badge b-q">Quantum</span>' if is_q else '<span class="badge b-cl">Classical</span>'
            css   = ' class="q-row"' if is_q else ""
            t_train = data.get("resource_usage", {}).get("training_time_seconds") if isinstance(data.get("resource_usage"), dict) else data.get("training_time")
            f1_val = m.get("f1_score", m.get("f1"))
            rows += (
                f"<tr{css}>"
                f"<td><strong>{name.replace('_', ' ').title()}</strong> {badge}</td>"
                f"<td>{_fmt_pct(m.get('accuracy'))}</td>"
                f"<td>{_fmt_pct(m.get('recall'))}</td>"
                f"<td>{_fmt_pct(m.get('specificity'))}</td>"
                f"<td>{_fmt_f(m.get('roc_auc'), 4)}</td>"
                f"<td>{_fmt_pct(f1_val)}</td>"
                f"<td>{_fmt_s(t_train)}</td>"
                f"</tr>\n"
            )

        n_models = len(ordered)
        return f"""
<h2>6. Model Comparison — All {n_models} Models</h2>
<table>
  <tr>
    <th>Model</th><th>Accuracy</th><th>Recall</th>
    <th>Specificity</th><th>ROC-AUC</th><th>F1</th><th>Train Time</th>
  </tr>
  {rows}
</table>"""

    def _s7_qvc_assessment(self, comparison: dict, cost_report: dict) -> str:
        # best_quantum comes from recommendation engine (dynamic, not hardcoded)
        best_q_info = comparison.get("best_quantum") or comparison.get("quantum_best") or "N/A"
        best_q_name = best_q_info.get("model_name", "N/A") if isinstance(best_q_info, dict) else str(best_q_info)

        best_cl_info = comparison.get("best_classical") or comparison.get("classical_best") or "N/A"
        best_cl_name = best_cl_info.get("model_name", "N/A") if isinstance(best_cl_info, dict) else str(best_cl_info)

        # Try to get performance_differences from recommendation output
        perf_diff = comparison.get("performance_differences", {})
        diff_rows = ""
        if perf_diff:
            for metric_key, delta in perf_diff.items():
                if not isinstance(delta, (int, float)):
                    continue
                colour = "#2e7d32" if delta > 0 else "#c62828"
                diff_rows += (
                    f"<tr><td>{metric_key.replace('_', ' ').title()}</td>"
                    f"<td style='color:{colour};font-weight:600'>"
                    f"{'+' if delta >= 0 else ''}{_fmt_f(delta, 4)}</td></tr>\n"
                )

        # Resource comparison from recommendation
        res_comp = comparison.get("resource_comparison", {})
        time_ratio = res_comp.get("training_time_ratio", "N/A") if res_comp else "N/A"
        q_circuits = res_comp.get("quantum_circuit_executions", "N/A") if res_comp else "N/A"
        q_qubits = res_comp.get("quantum_qubits", "N/A") if res_comp else "N/A"

        # Recommendation text from comparison (already dynamic from recommendation engine)
        rec_text = comparison.get("recommendation_text", "")
        if not rec_text:
            verdict = (cost_report.get("comparison_classical_baseline") or {}).get(
                "verdict", comparison.get("recommendation", "N/A")
            )
            rec_text = verdict

        # Build per-quantum-model performance table from performance_table
        perf_table = comparison.get("performance_table", [])
        q_rows = ""
        for row in perf_table:
            if row.get("model_type") == "QUANTUM":
                css = ' class="q-row"'
                badge = '<span class="badge b-q">Quantum</span>'
            else:
                css = ""
                badge = '<span class="badge b-cl">Classical</span>'
            q_rows += (
                f"<tr{css}>"
                f"<td><strong>{row.get('model_name', 'N/A')}</strong> {badge}</td>"
                f"<td>{_fmt_pct(row.get('recall'))}</td>"
                f"<td>{_fmt_f(row.get('roc_auc'), 4)}</td>"
                f"<td>{_fmt_s(row.get('training_time_seconds'))}</td>"
                f"</tr>\n"
            )

        return f"""
<h2>7. Quantum vs Classical Assessment</h2>
<p>
  Comparison is between the best classical model
  (<strong>{best_cl_name}</strong>) and the best quantum model
  (<strong>{best_q_name}</strong>).
</p>
{('<h3>Performance Differences (Quantum - Classical)</h3><table><tr><th>Metric</th><th>Delta</th></tr>' + diff_rows + '</table>') if diff_rows else ''}
{('<h3>Ranked Performance Table</h3><table><tr><th>Model</th><th>Recall</th><th>ROC-AUC</th><th>Train Time</th></tr>' + q_rows + '</table>') if q_rows else ''}
<table>
  <tr><th>Resource</th><th>Value</th></tr>
  <tr><td>Training time ratio (quantum / classical)</td><td>{time_ratio}x</td></tr>
  <tr><td>Quantum circuit executions</td><td>{q_circuits}</td></tr>
  <tr><td>Quantum qubits</td><td>{q_qubits}</td></tr>
</table>
<div class="rec">
  <div class="title">Assessment</div>
  <p>{rec_text}</p>
</div>
<p class="warn">
  Assessment is observed on this specific dataset and configuration. It does not
  constitute proof of general quantum advantage or disadvantage.
</p>"""

    def _s8_classical_importance(self, models: dict, explanations: dict) -> str:
        # Try to get from explanations dict first, fall back to RF gini importance
        for model_name in ("random_forest", "RandomForest"):
            rf_data = models.get("random_forest", {})
            fi_dict = (rf_data.get("metrics") or {}).get("feature_importance", {})
            if fi_dict and isinstance(fi_dict, dict):
                items = sorted(fi_dict.items(), key=lambda x: x[1], reverse=True)[:10]
                rows  = "".join(
                    f"<tr><td>{rank}</td><td>{feat}</td><td>{_fmt_f(imp, 4)}</td></tr>\n"
                    for rank, (feat, imp) in enumerate(items, 1)
                )
                return f"""
<h2>8. Feature Importance — Random Forest (Gini)</h2>
<p>
  Feature importances from the Random Forest model reflect the mean decrease in
  impurity across trees.  They describe which features the <em>model</em> relied
  on most — not direct clinical significance.
</p>
<table>
  <tr><th>Rank</th><th>Feature</th><th>Gini Importance</th></tr>
  {rows}
</table>
<p class="warn">
  Feature importance reflects model behaviour, not medical causality.
</p>"""

        # No feature importance data available
        exp_rf = explanations.get("random_forest", explanations.get("RandomForest", {}))
        gi     = exp_rf.get("global_importance", [])
        if gi:
            rows = "".join(
                f"<tr><td>{i+1}</td><td>{e.get('feature_name','?')}</td>"
                f"<td>{_fmt_f(e.get('importance'), 4)}</td></tr>\n"
                for i, e in enumerate(gi[:10])
            )
            return f"""
<h2>8. Feature Importance — Random Forest (SHAP)</h2>
<table>
  <tr><th>Rank</th><th>Feature</th><th>SHAP Importance</th></tr>
  {rows}
</table>"""

        return "<h2>8. Feature Importance — Random Forest</h2><p>Feature importance data not available.</p>"

    def _s9_quantum_importance(self, explanations: dict) -> str:
        exp = explanations.get("vqc", explanations.get("VQC", {}))
        gi  = exp.get("global_importance", []) or exp.get("feature_importance", [])

        if not gi:
            return f"""
<h2>9. Feature Importance — VQC (Perturbation-based)</h2>
<p>
  Perturbation-based importance was not computed for this experiment.
  To generate it, run the QuantumExplainer on the test set and attach
  the result to this report.
</p>
<p class="warn">
  Perturbation importance for the VQC reflects sensitivity of the quantum circuit
  output to each PCA component — not direct sensitivity to original clinical
  features.
</p>"""

        rows = "".join(
            f"<tr><td>{i+1}</td><td>{e.get('feature_name','?')}</td>"
            f"<td>{_fmt_f(e.get('importance'), 4)}</td></tr>\n"
            for i, e in enumerate(gi[:10])
        )
        return f"""
<h2>9. Feature Importance — VQC (Perturbation-based)</h2>
<p>
  Importance is measured as mean absolute change in VQC prediction score when
  each PCA component is individually replaced by its background mean.  This is
  a perturbation / feature occlusion approach — not a gradient-based method.
</p>
<table>
  <tr><th>Rank</th><th>Feature (PCA component)</th><th>Importance</th></tr>
  {rows}
</table>
<p class="warn">
  These importances describe the PCA components (latent dimensions), not original
  clinical features. They describe model sensitivity, not medical causality.
</p>"""

    def _s10_circuit_info(self, models: dict, explanations: dict) -> str:
        q_res = (models.get("vqc") or {}).get("metrics", {}).get("quantum_resources", {})
        n_q   = q_res.get("n_qubits", "?")
        n_l   = q_res.get("n_layers", "?")
        n_p   = q_res.get("n_params", "?")
        depth = q_res.get("circuit_depth", "?")

        exp = explanations.get("vqc", explanations.get("VQC", {}))
        ci  = exp.get("quantum_circuit_explanation", {})
        enc = ci.get("encoding_method", "angle_encoding")
        f2q = ci.get("feature_to_qubit_mapping", {})
        map_rows = "".join(
            f"<tr><td>{feat}</td><td>{qubit}</td></tr>"
            for feat, qubit in list(f2q.items())[:10]
        ) if f2q else ""

        return f"""
<h2>10. Quantum Circuit Information</h2>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Qubits</td>           <td>{n_q}</td></tr>
  <tr><td>Variational layers</td><td>{n_l}</td></tr>
  <tr><td>Trainable parameters</td><td>{n_p}</td></tr>
  <tr><td>Circuit depth</td>    <td>{depth}</td></tr>
  <tr><td>Encoding method</td>  <td>{enc}</td></tr>
  <tr><td>Measurement</td>      <td>PauliZ expectation on qubit 0</td></tr>
  <tr><td>Backend</td>          <td>PennyLane default.qubit (local simulator)</td></tr>
</table>
{('<h3>Feature-to-Qubit Mapping</h3><table><tr><th>PCA Feature</th><th>Qubit</th></tr>' + map_rows + '</table>') if map_rows else ''}
<p>
  <strong>Circuit structure:</strong>
  (1) Angle encoding — each PCA component maps to an RY rotation on one qubit;
  (2) Variational layers — trainable RY/RZ rotations + CNOT entanglement;
  (3) Measurement — PauliZ expectation value on qubit 0 maps to
  binary prediction via threshold 0.5.
</p>
<p class="warn">
  These results are from a local quantum simulator. They may differ on
  real quantum hardware due to gate noise and decoherence.
</p>"""

    def _s11_resource_usage(self, models: dict, resource_usage: dict) -> str:
        elapsed   = _safe_float(resource_usage.get("elapsed_time"))
        peak_mb   = _safe_float(resource_usage.get("peak_memory_mb"))
        cpu_avg   = _safe_float(resource_usage.get("cpu_percent"))
        peak_gb   = round(peak_mb / 1024, 3)

        model_rows = ""
        for name, data in models.items():
            if not data:
                continue
            mtype = str(data.get("model_type", "")).upper()
            is_q  = (mtype == "QUANTUM")
            badge = '<span class="badge b-q">Quantum</span>' if is_q else '<span class="badge b-cl">Classical</span>'
            ru = data.get("resource_usage", {}) if isinstance(data.get("resource_usage"), dict) else {}
            t_tr = ru.get("training_time_seconds", data.get("training_time"))
            t_inf = ru.get("inference_time_seconds", data.get("inference_time"))
            model_rows += (
                f"<tr><td>{name.replace('_', ' ').title()} {badge}</td>"
                f"<td>{_fmt_s(t_tr)}</td>"
                f"<td>{_fmt_s(t_inf)}</td></tr>\n"
            )

        return f"""
<h2>11. Resource Usage</h2>
<div class="cards">
  <div class="card"><div class="lbl">Total Wall Time</div><div class="val">{_fmt_s(elapsed)}</div></div>
  <div class="card"><div class="lbl">Peak RAM</div><div class="val">{peak_gb} GB</div></div>
  <div class="card"><div class="lbl">CPU Avg</div><div class="val">{cpu_avg:.1f}%</div></div>
</div>
<h3>Per-model Training and Inference Times</h3>
<table>
  <tr><th>Model</th><th>Training Time</th><th>Inference Time</th></tr>
  {model_rows}
</table>
<p>
  Resource measurements use <code>time.perf_counter()</code> for wall-clock time
  and <code>psutil</code> for RAM. Quantum circuit execution count is tracked
  by the VQCModel training loop.
</p>"""

    def _s12_cost_analysis(self, cost_report: dict) -> str:
        q    = cost_report.get("quantum_cost", {})
        pcb  = cost_report.get("pipeline_cost_breakdown", {})
        ccb  = cost_report.get("comparison_classical_baseline", {})
        fin  = cost_report.get("financial_cost_local", {})
        sca  = cost_report.get("scalability_assessment", {})

        return f"""
<h2>12. Cost Analysis</h2>
<h3>Quantum Resource Usage</h3>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Qubits used</td>              <td>{q.get('qubits', 'N/A')}</td></tr>
  <tr><td>Circuit depth</td>            <td>{q.get('circuit_depth', 'N/A')}</td></tr>
  <tr><td>Total circuit executions</td> <td>{q.get('total_circuit_executions', 'N/A')}</td></tr>
  <tr><td>Shots per execution</td>      <td>{q.get('shots_per_execution', 'exact (no shots)')}</td></tr>
  <tr><td>Training time (VQC)</td>
      <td>{_fmt_s((cost_report.get('computational_cost') or {}).get('training', {}).get('wall_clock_time_seconds'))}</td></tr>
</table>
<h3>Pipeline Cost Breakdown</h3>
<table>
  <tr><th>Stage</th><th>Time</th></tr>
  <tr><td>Preprocessing (estimate)</td><td>{_fmt_s(pcb.get('preprocessing_seconds'))}</td></tr>
  <tr><td>Quantum training</td>        <td>{_fmt_s(pcb.get('quantum_training_seconds'))}</td></tr>
  <tr><td>Total pipeline</td>          <td>{_fmt_s(pcb.get('total_pipeline_seconds'))}</td></tr>
  <tr><td>Quantum % of total</td>      <td>{pcb.get('quantum_percentage', 'N/A')}%</td></tr>
</table>
<h3>Classical vs Quantum Speed</h3>
<table>
  <tr><th>Model</th><th>Training Time</th></tr>
  <tr><td>{ccb.get('classical_model', 'Best classical').replace('_',' ').title()}</td>
      <td>{_fmt_s(ccb.get('classical_training_secs'))}</td></tr>
  <tr><td>VQC</td><td>{_fmt_s(ccb.get('quantum_training_secs'))}</td></tr>
  <tr><td>Speed ratio (VQC / classical)</td><td>{ccb.get('speedup_classical', 'N/A')}×</td></tr>
</table>
<h3>Financial Cost</h3>
<table>
  <tr><th>Item</th><th>Value</th></tr>
  <tr><td>Execution mode</td>      <td>LOCAL_LAPTOP</td></tr>
  <tr><td>Financial estimate</td>  <td><strong>0</strong> (local execution)</td></tr>
  <tr><td>Note</td>                <td>{fin.get('note', '')}</td></tr>
</table>
<h3>Scalability Assessment</h3>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Environment</td>    <td>{sca.get('current_environment', 'LOCAL_LAPTOP')}</td></tr>
  <tr><td>Status</td>         <td><strong>{sca.get('this_experiment_status', 'FEASIBLE')}</strong></td></tr>
  <tr><td>Recommended max qubits</td><td>{sca.get('recommended_max_qubits', 8)}</td></tr>
  <tr><td>Note</td>           <td>{sca.get('note', '')}</td></tr>
</table>"""

    def _s13_pipeline_trace(
        self, explanations: dict, configuration: dict
    ) -> str:
        trace: List[dict] = []
        for exp in explanations.values():
            t = exp.get("pipeline_trace", [])
            if t:
                trace = t
                break

        if not trace:
            # Build minimal trace from config
            trace = [
                {"phase": "Phase 1",  "component": "Dataset Ingestion",  "artifact": "dataset"},
                {"phase": "Phase 4",  "component": "Preprocessing",       "artifact": "StandardScaler"},
                {"phase": "Phase 6",  "component": "Feature Reduction",   "artifact": "PCA",
                 "method": "PCA"},
                {"phase": "Phase 8",  "component": "Classical Models",    "artifact": "sklearn"},
                {"phase": "Phase 8",  "component": "Quantum Model",       "artifact": "VQC"},
                {"phase": "Phase 10", "component": "Evaluation",          "artifact": "benchmarking"},
                {"phase": "Phase 12", "component": "Explainability",      "artifact": "Phase 12"},
            ]

        rows = "".join(
            f"<tr><td>{t.get('phase','')}</td>"
            f"<td>{t.get('component','')}</td>"
            f"<td><code>{t.get('artifact','')}</code></td>"
            f"<td>{t.get('method') or t.get('backend') or t.get('description','')}</td>"
            f"</tr>\n"
            for t in trace
        )
        return f"""
<h2>13. Pipeline Lineage</h2>
<p>
  Every prediction is traceable through the following pipeline stages.
  Data leakage is prevented by fitting all transformations on training data only
  and applying them to test data separately.
</p>
<table>
  <tr><th>Phase</th><th>Component</th><th>Artifact</th><th>Details</th></tr>
  {rows}
</table>"""

    def _s14_limitations(self) -> str:
        return """
<h2>14. Limitations</h2>
<ul>
  <li>
    <strong>Local simulator only.</strong>
    All quantum results are from a statevector simulator (PennyLane
    <code>default.qubit</code>). Real quantum hardware introduces noise,
    decoherence, and gate errors that may change results.
  </li>
  <li>
    <strong>Dataset-specific.</strong>
    Conclusions (including any observed quantum performance differences) apply
    to the evaluated dataset and configuration only. They must not be generalised
    without further validation.
  </li>
  <li>
    <strong>Uncalibrated scores.</strong>
    Prediction scores are not calibrated. They must not be interpreted as
    clinical probabilities.
  </li>
  <li>
    <strong>Explainability ≠ causality.</strong>
    SHAP values and perturbation importances describe how the model uses
    features — not how features cause the outcome clinically.
  </li>
  <li>
    <strong>PCA features.</strong>
    The quantum model operates on PCA components, not original clinical
    features. Feature importance for VQC refers to latent dimensions, not
    directly to measurable biomarkers.
  </li>
  <li>
    <strong>Small dataset size.</strong>
    Results may not generalise to larger or more diverse patient populations.
  </li>
  <li>
    <strong>Not a clinical system.</strong>
    This platform is a research and benchmarking tool.
    It is not validated for clinical use.
  </li>
</ul>"""

    def _s15_conclusion(self, comparison: dict) -> str:
        rec = comparison.get("recommendation", "See model comparison section.")
        best = comparison.get("best_model", "N/A")
        best_cl = comparison.get("best_classical", "N/A")

        # Derive plain-language conclusion label from the recommendation string
        rec_upper = rec.upper()
        if "QUANTUM ADVANTAGE" in rec_upper or "QUANTUM BENEFIT" in rec_upper:
            label = "PROMISING QUANTUM RESULT (observed on this dataset)"
        elif "PARITY" in rec_upper or "COMPARABLE" in rec_upper:
            label = "PERFORMANCE PARITY"
        elif "CLASSICAL" in rec_upper and (
            "PREFERRED" in rec_upper or "SUPERIOR" in rec_upper
        ):
            label = "CLASSICAL MODEL PREFERRED"
        elif "RECALL" in rec_upper:
            label = "QUANTUM RECALL ADVANTAGE (observed)"
        else:
            label = "INCONCLUSIVE / INSUFFICIENT EVIDENCE"

        return f"""
<h2>15. Conclusion</h2>
<div class="rec">
  <div class="title">Observed outcome: {label}</div>
  <p>{rec}</p>
</div>
<ul>
  <li>Best overall model observed: <strong>{best.replace('_', ' ').title()}</strong></li>
  <li>Best classical model observed: <strong>{best_cl.replace('_', ' ').title()}</strong></li>
</ul>
<p class="warn">
  <strong>Research language notice:</strong>
  All findings use "observed" qualifiers. This report does not claim general
  quantum advantage, does not claim medical causality, and does not claim
  clinical efficacy. Results are specific to the evaluated dataset, split,
  and experimental configuration.
</p>"""

    def _s16_reproduction(self, experiment_id: str, configuration: dict) -> str:
        rng    = configuration.get("random_state", 42)
        n_comp = configuration.get("n_components", "?")
        q_cfg  = configuration.get("quantum_config", {})
        layers = q_cfg.get("layers", 2)
        shots  = q_cfg.get("shots", "exact")

        return f"""
<h2>16. Reproduction Information</h2>
<table>
  <tr><th>Parameter</th><th>Value</th></tr>
  <tr><td>Experiment ID</td>   <td><code>{experiment_id}</code></td></tr>
  <tr><td>Random state</td>    <td>{rng}</td></tr>
  <tr><td>PCA components</td>  <td>{n_comp}</td></tr>
  <tr><td>VQC layers</td>      <td>{layers}</td></tr>
  <tr><td>Shots (record)</td>  <td>{shots}</td></tr>
  <tr><td>Train/test split</td><td>80/20 stratified</td></tr>
  <tr><td>Quantum backend</td> <td>PennyLane default.qubit</td></tr>
  <tr><td>Platform</td>        <td>Q-Diagnose MVP — Quant Warriors SIH 2026</td></tr>
</table>
<p>
  To reproduce: load the experiment by ID from
  <code>artifacts/experiments/{experiment_id}.json</code>
  and re-run using <code>run_experiment.py</code> with the same configuration.
  Variational quantum optimisation may produce slightly different results
  due to floating-point non-determinism across environments.
</p>"""

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _cards(items: List[tuple]) -> str:
        inner = "".join(
            f'<div class="card">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val">{value}</div>'
            f'</div>'
            for label, value in items
        )
        return f'<div class="cards">{inner}</div>'

    def save(self, html: str, experiment_id: str) -> str:
        """Write the HTML report to disk.

        Saves to ``artifacts/reports/{experiment_id}_report.html``.

        Parameters
        ----------
        html : str
            HTML string produced by ``generate()``.
        experiment_id : str
            Used to construct the filename.

        Returns
        -------
        str — absolute path to the written file.
        """
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        path = REPORTS_DIR / f"{experiment_id}_report.html"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(html)
        logger.info(f"ReportGenerator: report saved -> {path}")
        return str(path)

    def generate_and_save(
        self,
        experiment: dict,
        cost_report: Optional[dict] = None,
        explanations: Optional[dict] = None,
    ) -> str:
        """Convenience: generate then save.

        Returns
        -------
        str — path to the saved file.
        """
        html = self.generate(experiment, cost_report, explanations)
        return self.save(html, experiment.get("id", "UNKNOWN"))
